modLoader = "javafml"
loaderVersion = "[1,)"
license = "GNU LGPL 3.0"

[[mods]]
modId = "mixin_args"
version = "${file.jarVersion}"
displayName = "Mixin ModifyArgs Shim"
authors = "screret"
displayTest = "IGNORE_ALL_VERSION"
description = '''A simple mod that adds the packages necessary for Mixin's ModifyArgs to work.'''

[[dependencies.mixin_args]]
modId = "neoforge"
type = "required"
versionRange = ""
ordering = "NONE"
side = "BOTH"